/**
 * Three routes for one branch, each naming its risk level and what it forecloses.
 *
 * This is the instrument for the tree node "Offer three routes at different risk
 * levels and say what each one forecloses", under the assumption test "Produce
 * three routes for one live branch and have a reader rank them without seeing
 * the labels". The spec is the solution node's own sentence: three routes come
 * back for one branch, each naming its risk level and what choosing it
 * forecloses, with the foreclosed sets differing between them — a route that
 * forecloses nothing, or repeats a sibling's trade-off, fails.
 *
 * The node's own objection is what most of this file is aimed at: three routes
 * are "the option most likely to be generated by a model with no real basis for
 * the risk levels it assigns". So the pins here are not that a `risk` field is
 * present — a fiction has a risk field too — but that the field is *derived*:
 * every route's stated level equals what {@link riskOf} reads off that route's
 * own steps, and every foreclosure names a node that is really in the branch.
 *
 * What a green here does NOT settle, and the assumption test says so itself: the
 * blind ranking. Whether a reader shown the three with the labels stripped
 * reproduces this order needs a reader, and stays with a human. Compute can
 * guarantee three routes exist, differ, and each say what it costs; it cannot
 * check that the ranking is right.
 */
import { describe, expect, test } from "vitest";
import {
  foreclosureProblem,
  renderRoutes,
  riskOf,
  routesFor,
  FORECLOSURE_KINDS,
  ROUTE_IDS,
  RISK_LEVELS,
  type Route,
} from "../../src/ost/routes.js";
import type { OstNode } from "../../src/ost/node.js";

const BRANCH = "Checking on progress means digging through files";
const SOLUTION_A = "A status line the loop prints at every phase boundary";
const SOLUTION_B = "A dashboard page regenerated after every pass";
const BELIEF_SHARED = "Progress is legible at all from what the loop already records";
const BELIEF_A = "An operator reads a status line rather than opening the files";
const BELIEF_B = "A page is worth what regenerating it costs every pass";
const TEST_SHARED = "Reconstruct last week's progress from the loop's records alone";
const TEST_A = "Count how often the operator opens a file after the line prints";
const TEST_B = "Time the regeneration against the pass it hangs off";

function node(partial: Partial<OstNode> & Pick<OstNode, "title" | "layer">): OstNode {
  return { tags: [], links: [], body: "x", ...partial };
}

/** A test whose instrument has been observed failing — i.e. a live build permit. */
function redTest(title: string, spec: string): OstNode {
  return node({
    title,
    layer: "AssumptionTest",
    instrument: `npx vitest run test/x/${spec}.test.ts`,
    body: [
      "The belief this measures.",
      "",
      "## Instrument Log",
      `- 2026-08-20 **red** (exit 1) \`npx vitest run test/x/${spec}.test.ts\` — not built yet`,
    ].join("\n"),
  });
}

/**
 * A branch shaped like a live one: two buildable solutions, three unmeasured
 * beliefs, one of which both solutions rest on. The shared belief is the one
 * whose failure kills the most of the branch, which is what makes
 * "test the riskiest first" a different route from "test everything first".
 */
function liveBranch(): OstNode[] {
  return [
    node({ title: BRANCH, layer: "Opportunity", links: [SOLUTION_A, SOLUTION_B] }),
    node({ title: SOLUTION_A, layer: "Solution", links: [BELIEF_A, BELIEF_SHARED] }),
    node({ title: SOLUTION_B, layer: "Solution", links: [BELIEF_B, BELIEF_SHARED] }),
    node({ title: BELIEF_A, layer: "Assumption", links: [TEST_A] }),
    node({ title: BELIEF_B, layer: "Assumption", links: [TEST_B] }),
    node({ title: BELIEF_SHARED, layer: "Assumption", links: [TEST_SHARED] }),
    redTest(TEST_A, "status-line"),
    redTest(TEST_B, "dashboard"),
    redTest(TEST_SHARED, "legibility"),
  ];
}

function routesOf(tree: readonly OstNode[]): Route[] {
  const result = routesFor(tree, BRANCH);
  if (result.kind !== "routes") throw new Error(`expected routes, got too-thin: ${result.why}`);
  return result.routes;
}

describe("three routes come back for one branch", () => {
  test("exactly three, one per route id", () => {
    const routes = routesOf(liveBranch());
    expect(routes).toHaveLength(3);
    expect(routes.map((r) => r.id).sort()).toEqual([...ROUTE_IDS].sort());
  });

  test("each names a risk level, and the three are three different levels", () => {
    const routes = routesOf(liveBranch());
    for (const r of routes) expect(RISK_LEVELS).toContain(r.risk);
    // Three routes at ONE risk level is one route offered three times.
    expect(new Set(routes.map((r) => r.risk)).size).toBe(3);
  });

  test("each carries steps a builder could actually take, naming real nodes", () => {
    const tree = liveBranch();
    const titles = new Set(tree.map((n) => n.title));
    for (const r of routesOf(tree)) {
      expect(r.steps.length).toBeGreaterThan(0);
      for (const s of r.steps) expect(titles).toContain(s.node);
    }
  });
});

describe("the risk level is derived from the route, not assigned to it", () => {
  test("every route's stated risk equals what its own steps say", () => {
    // The node's objection is a model inventing risk levels. This is the pin:
    // the field is not free text, it is a function of the steps, and if the
    // steps changed the level would change with them.
    const unrun = 3;
    for (const r of routesOf(liveBranch())) {
      expect(r.risk).toBe(riskOf(r.steps, unrun));
    }
  });

  test("committing before measuring anything is high, measuring everything first is low", () => {
    const build = { act: "build", node: SOLUTION_A } as const;
    const t1 = { act: "test", node: TEST_A } as const;
    const t2 = { act: "test", node: TEST_B } as const;
    expect(riskOf([build, t1, t2], 2)).toBe("high");
    expect(riskOf([t1, t2, build], 2)).toBe("low");
    // Some evidence, then commitment, with measurements still outstanding.
    expect(riskOf([t1, build, t2], 2)).toBe("medium");
  });

  test("the route that builds first is the high one, and it is not the safe one", () => {
    const routes = routesOf(liveBranch());
    const byId = new Map(routes.map((r) => [r.id, r]));
    expect(byId.get("commit-early")?.risk).toBe("high");
    expect(byId.get("learn-first")?.risk).toBe("low");
    expect(byId.get("riskiest-belief-first")?.risk).toBe("medium");
  });
});

describe("the riskiest belief says whether the tree chose it", () => {
  test("a belief more solutions rest on than any other is chosen on blast radius", () => {
    const byId = new Map(routesOf(liveBranch()).map((r) => [r.id, r]));
    const route = byId.get("riskiest-belief-first")!;
    expect(route.basis).toBe("blast-radius");
    expect(route.summary).toContain(BELIEF_SHARED);
    expect(route.summary).toMatch(/more than any other/);
  });

  test("when every belief has the same blast radius, the route admits a tie-break chose it", () => {
    // This is the shape of this product's own vault, measured 2026-08-28: each
    // solution states its own assumptions and none are shared, so nothing in the
    // tree ranks them. The route must not present that as a risk ranking.
    const tree = liveBranch().map((n) =>
      // Drop the shared belief from B, leaving every belief with exactly one
      // dependent solution and no blast radius to separate them.
      n.title === SOLUTION_B ? node({ ...n, links: [BELIEF_B] }) : n,
    );
    const result = routesFor(tree, BRANCH);
    if (result.kind !== "routes") throw new Error(`expected routes: ${result.why}`);
    const route = result.routes.find((r) => r.id === "riskiest-belief-first")!;
    expect(route.basis).toBe("tie-break");
    expect(route.summary).toMatch(/the tree did not choose it/);
    expect(route.summary).toMatch(/not a risk ranking/);
  });

  test("only the riskiest-first route carries a basis at all", () => {
    for (const r of routesOf(liveBranch())) {
      if (r.id === "riskiest-belief-first") expect(r.basis).toBeDefined();
      else expect(r.basis).toBeUndefined();
    }
  });

  test("a tie-break is repeated in the rendered page, not left in one sentence", () => {
    const tree = liveBranch().map((n) => (n.title === SOLUTION_B ? node({ ...n, links: [BELIEF_B] }) : n));
    const rendered = renderRoutes(routesFor(tree, BRANCH));
    expect(rendered).toMatch(/chosen by a tie-break rather than by blast radius/);
    // …and it is absent when the tree really did rank the beliefs.
    expect(renderRoutes(routesFor(liveBranch(), BRANCH))).not.toMatch(/tie-break/);
  });
});

describe("the forecloses field is the whole solution", () => {
  test("no route forecloses nothing", () => {
    for (const r of routesOf(liveBranch())) expect(r.forecloses.length).toBeGreaterThan(0);
  });

  test("every foreclosure names a node in the branch and a recognised kind", () => {
    const tree = liveBranch();
    const titles = new Set(tree.map((n) => n.title));
    for (const r of routesOf(tree)) {
      for (const f of r.forecloses) {
        expect(FORECLOSURE_KINDS).toContain(f.kind);
        expect(titles).toContain(f.target);
        expect(f.what.trim().length).toBeGreaterThan(0);
      }
    }
  });

  test("the foreclosed sets differ, and none is a subset of the others", () => {
    expect(foreclosureProblem(routesOf(liveBranch()))).toBeNull();
  });

  test("each route gives up something specific the others keep", () => {
    const byId = new Map(routesOf(liveBranch()).map((r) => [r.id, r]));
    const kinds = (id: (typeof ROUTE_IDS)[number]) => new Set(byId.get(id)!.forecloses.map((f) => f.kind));
    // Building early costs the clean reading on the tests beneath what it built.
    expect(kinds("commit-early")).toContain("clean-read");
    // Testing one belief first leaves the others unmeasured behind it.
    expect(kinds("riskiest-belief-first")).toContain("deferred-belief");
    // Measuring everything first buys readings a failed riskiest belief moots.
    expect(kinds("learn-first")).toContain("moot-measurement");
  });

  test("the shared cost really is shared — both waiting routes defer the same permits", () => {
    const byId = new Map(routesOf(liveBranch()).map((r) => [r.id, r]));
    const permits = (id: (typeof ROUTE_IDS)[number]) =>
      byId.get(id)!.forecloses.filter((f) => f.kind === "unspent-permit").map((f) => f.target).sort();
    expect(permits("learn-first")).toEqual([SOLUTION_A, SOLUTION_B].sort());
    expect(permits("riskiest-belief-first")).toEqual(permits("learn-first"));
    // …and it is not the whole of either route's cost, or one would be dominated.
    expect(foreclosureProblem(routesOf(liveBranch()))).toBeNull();
  });
});

describe("a route set that is not a real choice is refused", () => {
  const real = (): Route[] => routesOf(liveBranch());

  test("a route that forecloses nothing fails the check", () => {
    const routes = real();
    routes[0] = { ...routes[0], forecloses: [] };
    expect(foreclosureProblem(routes)).toMatch(/forecloses nothing/);
  });

  test("a route repeating a sibling's trade-off fails the check", () => {
    const routes = real();
    routes[1] = { ...routes[1], forecloses: routes[0].forecloses };
    expect(foreclosureProblem(routes)).toMatch(/exactly the same things/);
  });

  test("a route whose costs are all borne by a sibling too is dominated, and fails", () => {
    const routes = real();
    // Every cost of route 0, minus nothing of its own — a strict subset of a
    // sibling's set. An operator comparing costs would never pick it.
    routes[0] = { ...routes[0], forecloses: [routes[1].forecloses[0]] };
    expect(foreclosureProblem(routes)).toMatch(/dominated/);
  });
});

describe("a branch too thin for three routes refuses instead of padding", () => {
  test("nothing cleared to build means there is no commit-early route", () => {
    // Same branch, but no test declares an instrument, so no build permit is live.
    const tree = liveBranch().map((n) =>
      n.layer === "AssumptionTest" ? node({ ...n, instrument: undefined, body: "no instrument" }) : n,
    );
    const result = routesFor(tree, BRANCH);
    expect(result.kind).toBe("too-thin");
    if (result.kind !== "too-thin") return;
    expect(result.why).toMatch(/live build permit/);
    expect(result.whatWouldHelp.length).toBeGreaterThan(0);
  });

  test("one live belief means riskiest-first is the same route as learn-first", () => {
    const tree: OstNode[] = [
      node({ title: BRANCH, layer: "Opportunity", links: [SOLUTION_A] }),
      node({ title: SOLUTION_A, layer: "Solution", links: [BELIEF_A] }),
      node({ title: BELIEF_A, layer: "Assumption", links: [TEST_A] }),
      redTest(TEST_A, "status-line"),
    ];
    const result = routesFor(tree, BRANCH);
    expect(result.kind).toBe("too-thin");
    if (result.kind !== "too-thin") return;
    expect(result.why).toMatch(/1 belief\(s\) with an unmeasured test/);
  });

  test("a branch with nothing left to measure has no learn-first route", () => {
    const tree = liveBranch().map((n) =>
      n.layer === "AssumptionTest" ? node({ ...n, body: `${n.body}\n\n## Results\n- 2026-08-21 measured` }) : n,
    );
    const result = routesFor(tree, BRANCH);
    expect(result.kind).toBe("too-thin");
    if (result.kind !== "too-thin") return;
    expect(result.why).toMatch(/still unmeasured/);
  });

  test("a refusal is never two routes dressed as three", () => {
    const tree = liveBranch().map((n) =>
      n.layer === "AssumptionTest" ? node({ ...n, instrument: undefined, body: "no instrument" }) : n,
    );
    const result = routesFor(tree, BRANCH);
    expect("routes" in result).toBe(false);
  });
});

describe("the branch has to be a branch", () => {
  test("a title that is not an Opportunity is refused outright", () => {
    expect(() => routesFor(liveBranch(), SOLUTION_A)).toThrow(/no Opportunity node titled/);
    expect(() => routesFor(liveBranch(), "Nothing by this name")).toThrow(/no Opportunity node titled/);
  });
});

describe("two runs over one tree say the same thing", () => {
  test("the riskiest belief, the order, and the costs are stable", () => {
    // A "riskiest" that moves between runs is not a risk ranking, and a reader
    // asked to rank three routes blind must be ranking the same three twice.
    expect(JSON.stringify(routesOf(liveBranch()))).toBe(JSON.stringify(routesOf(liveBranch())));
  });
});
