/**
 * OST_RULESET — machine-usable rules distilled from Teresa Torres's Opportunity
 * Solution Tree methodology (Continuous Discovery Habits, 2021).
 *
 * Generated by the ost-research workflow (adversarially verified per dimension) and
 * consumed by the discovery processes' system prompts and definition-of-done checks.
 * The prose companion is docs/reference/teresa-torres-ost.md. Edit deliberately —
 * changing a rule changes agent behavior.
 */

export const OST_RULESET = {
  "layers": [
    {
      "tag": "#Outcome",
      "name": "Outcome",
      "definition": "The single desired outcome at the root that scopes all discovery; should be a product outcome (a customer behavior in the product or sentiment about it, within the team's control), not a business/financial metric or an output like 'ship feature X'.",
      "role": "Root; one per tree; assigned by leadership, never invented or changed by the agent."
    },
    {
      "tag": "#Opportunity",
      "name": "Opportunity",
      "definition": "An unmet customer need, pain point, or desire, phrased from the customer's perspective and sourced from customer interviews; never a solution or feature. Opportunities nest into a multi-level sub-tree (an opportunity can parent other opportunities).",
      "role": "Customer-value layer connecting the outcome to solutions; siblings are distinct alternatives, parent-child pairs are subset relationships."
    },
    {
      "tag": "#Solution",
      "name": "Solution",
      "definition": "A product, feature, service, workflow, process, documentation, or anything else offered to address a known opportunity. Attaches to the single target opportunity it addresses.",
      "role": "Candidate to be compared and de-risked; generate multiple per target opportunity; enters the tree unvalidated."
    },
    {
      "tag": "#Assumption",
      "name": "Assumption",
      "definition": "One belief a solution depends on, stated so that it could turn out to be false — 'operators will hand a secret to a broker', not 'the broker works'. Torres's four kinds are the vocabulary: desirability, viability, feasibility, usability. A solution rests on several, and they are what get compared when choosing between solutions.",
      "role": "Sits between a solution and its tests; attaches beneath the solution whose risk it names. Keeping it separate is what stops a solution resting on four beliefs from reading as covered because one test passed."
    },
    {
      "tag": "#AssumptionTest",
      "name": "Assumption test",
      "definition": "A small, fast test of ONE assumption, used to choose among solutions rather than validate one whole idea. It names either the command whose exit code answers it or the person who is irreducibly the measurement.",
      "role": "Bottom layer; attaches beneath the specific assumption it probes, not directly under the solution; proposed by the agent, run only by humans."
    }
  ],
  "firstRun": [
    "A session can be connected to these tools before any vault exists — that is the normal first minute, not a malfunction. `ost_next_work` reports it as `bootstrap: true` with a `reason` and a `nextStep`; treat that as the state of the world and follow the branch below instead of reporting a broken tool.",
    "When `reason` is `no-vault`: ask the human what outcome they want this tree to serve, in one sentence, and wait for their answer. Then read their words back to them and set the vault up by running the payload's own `nextStep` command, substituting ONLY their sentence for the single `<…>` placeholder in it. Do not retype the folder: `nextStep` already names the directory the server is pointed at, and a path taken from your own shell's cwd can be a different one — that scaffolds a vault the server never reads, so `ost_next_work` still answers `bootstrap: true` and the human is asked the same question a second time having already answered it correctly.",
    "When `reason` is `no-outcome`: the vault exists but its root is missing; ask the human for the outcome and use `node ${CLAUDE_PLUGIN_ROOT}/dist/ost-agent.mjs set-outcome \"<their words>\" --vault <dir>`.",
    "Never invent, paraphrase into something sharper, or guess the outcome — it is the single human-set mandate the whole tree hangs from, and inventing it would make every node below it ladder up to a goal nobody chose.",
    "If the human is not available to answer, stop and say what you are waiting for. Do not scaffold a vault around a placeholder outcome to make progress.",
    "Setting up a vault needs no model and no API key, and neither does anything else here — `status`, `check`, `debt`, `lanes`, `result`, and every tool on this surface are deterministic. This project calls no model at all: the server holds none, and the connected session supplies every bit of the reasoning.",
    "Once the vault is set up, call `ost_next_work` again and continue into the normal maintenance loop; a fresh tree with only an Outcome is legitimately `done`, and the next thing it needs is evidence, not ideation.",
    "`/ost-setup` is the front door onto this same branch, named in the slash-command menu so that someone who has just installed the plugin can find it without already knowing to ask for discovery work. Reporting first run is not the same as being findable: if a human seems to be starting from nothing, say `/ost-setup` out loud rather than waiting to be asked."
  ],
  "treeRules": [
    "Exactly one desired outcome sits at the root; multiple outcomes mean multiple trees.",
    "The tree flows strictly downward: Outcome -> Opportunities (nested) -> Solutions -> Assumptions -> Assumption Tests, with each node mapping to its parent.",
    "Write a `[[wikilink]]` to a node ONLY as its parent's child edge. A title is wikilinked exactly once in the whole vault, so anywhere else — a cross-reference in prose, a duplicate flagged under `## Issues`, a definition of done, a line in `## History` — name the node in plain quoted text instead: \"Some node\". A mention costs nothing and says the same thing; a link makes the graph a web. `check` fails on a second link (rule single-backlink). This is why an edge is the only place brackets belong.",
    "Place each node under its single best-fit parent. This is enforced, not advised: a node has exactly one parent, `ost_link_nodes` refuses a second edge onto an already-parented node, and `check` fails on one (rule single-parent). If a node plausibly fits two parents, that is a judgement about which it serves best and the tree records one answer — flag it for human review rather than double-linking. To move a node, detach it from the old parent and then link it under the new one.",
    "Opportunities form a multi-level sub-tree: an opportunity node may be the parent of other opportunity nodes; the tree is not four flat levels.",
    "Parent-child opportunity relationships represent subsets; sibling relationships represent distinct alternatives at the same level.",
    "Every solution must address at least one opportunity in the tree; no orphan solutions.",
    "Every assumption test maps to exactly one assumption, and every assumption to exactly one solution.",
    "Sibling opportunities should be distinct from one another; the tree is deliberately incomplete and evolving, and siblings need not be collectively exhaustive.",
    "The tree is a living artifact: when evidence invalidates a branch, re-chart it (evolve the solution, pick a different opportunity, or flag the outcome) rather than discarding the rest of the tree."
  ],
  "opportunityRules": [
    "State every opportunity as an unmet customer need, pain point, or desire from the customer's perspective, never as a solution, feature, or business ask.",
    "Apply the litmus test 'Is there more than one way to address this opportunity?': if only one implementation fits, it is a solution in disguise and belongs one layer down or must be reframed upward into the underlying need.",
    "Source opportunities from story-based, past-behavior customer interviews rather than internal brainstorming.",
    "Derive top-level opportunities from key moments in a customer experience map, then nest sub-opportunities under the relevant parent.",
    "Reframe solution-shaped or business-shaped inputs into need-shaped opportunities, or hold them for human review; never assert them as validated needs.",
    "Attach every opportunity so it ladders up to the desired outcome."
  ],
  "solutionRules": [
    "Attach each solution to the single target opportunity it addresses.",
    "Generate multiple competing solutions per target opportunity (aim for at least three) and narrow to a consideration set.",
    "Compare and contrast solutions against each other rather than validating a single idea in isolation ('good' is judgeable only relative to alternatives).",
    "Prefer generating more solutions especially when there is risk, when the opportunity is a differentiator, or when innovation is needed.",
    "Target one opportunity at a time (a work-in-progress limit) and go deep before moving on.",
    "Every agent-originated solution enters the tree unvalidated — the marker is stamped by the server, not chosen by the author — and `validated` is not a status the agent can set at all; promotion is a human's call on the CLI."
  ],
  "assumptionCategories": [
    "desirability",
    "viability",
    "feasibility",
    "usability"
  ],
  "assumptionRules": [
    "Surface the underlying assumptions a solution depends on and test the riskiest ones, rather than testing the whole solution.",
    "Classify each assumption into one of the four risk categories: desirability, viability, feasibility, or usability (also consider potential-harm/ethical assumptions as an additional check).",
    "Keep each test small and fast, with a success threshold pre-committed before running.",
    "Use assumption-test results as comparative evidence to choose among solutions, not as a yes/no verdict on one idea.",
    "The agent may propose test designs but must never run tests or record test results as evidence; humans run tests with real customers/data.",
    "Ask of every assumption, before reaching for an interview: could the repository answer this? A feasibility assumption about code — whether a guard refuses, whether a path resolves, whether an exit code is what the node claims — is settled by a spec file in minutes and does not need anybody's afternoon. Reaching for a customer study when the answer is on disk spends the scarcest resource in the process on a question that was never about customers.",
    "Every test must name one of two things: an `instrument` — a single spec-file command whose exit code answers it — or the person who is irreducibly the measurement. A test that names neither is refused at the tool boundary, and that refusal is the point: prose states what would count as an answer, an instrument IS the answer, run, and a test with only a threshold can be settled by nobody but a person finding the time. That is how a tree comes to hold hundreds of tests and hand its builder nothing.",
    "Go back and re-write the tests that were written before this rule. A test with a threshold and no runnable form is not finished work, it is debt, and `ost_set_instrument` is how it gets paid: read the test's own threshold and write the command that would settle it. This is giving an existing question a runnable form, not inventing a new question, so the test keeps its identity and its history.",
    "An instrument must be RED when it is written: it names behaviour that does not exist yet, so the command fails against the repository today and passes only once the solution is real. A command that already passes is a description of the present, not a test — it cannot fail, so it measures nothing and gives a builder no definition of done. This is the one property that makes an agent-authored test worth anything, because it is a falsifiable prediction rather than a claim.",
    "Say what an instrument does NOT settle, in the test's own prose. A green spec proves the code does what the node said; it never proves anyone wanted it. Feasibility answered mechanically leaves desirability, viability and usability exactly where they were, and a node that does not say so invites a reader to mistake a passing test for a validated solution."
  ],
  "prioritization": [
    "Prioritize opportunities, not solutions; the strategic decision is which customer need to target.",
    "Prioritize row by row: assess top-level opportunities, pick the top branch, then drill into that branch's children.",
    "Assess opportunity sizing qualitatively (how many customers are impacted, and how often), not with a multiplicative reach x frequency formula.",
    "Weigh customer factors (importance to customers), market factors (effect on market position), and company factors (fit with vision, mission, and strategy).",
    "Estimate how much impact addressing each opportunity would have on the desired outcome.",
    "Do not use quantified scoring formulas (e.g. RICE); treat prioritization as messy, subjective, reversible two-way-door decisions where speed beats false precision.",
    "Opportunity and solution selection are human decisions; the agent may surface sizing information but must not auto-select a target opportunity or a winning solution."
  ],
  "cadence": [
    "Continuous discovery means at a minimum weekly touchpoints with customers by the team building the product, where they conduct small research activities toward a desired outcome.",
    "Work one outcome (one tree) at a time.",
    "Conduct weekly story-based customer interviews to source and refine opportunities from real unmet needs.",
    "Map and structure the opportunity space, then prioritize opportunities row by row and select a single target opportunity at a time.",
    "Generate multiple solutions for the target opportunity, then run small, fast assumption tests continuously instead of one big up-front validation.",
    "Update the tree as interviews and tests land, and revisit or re-chart a branch when evidence invalidates it."
  ],
  "agentMust": [
    "Treat itself as a cartographer of the team's knowledge: organize, represent, and question, but never generate or validate knowledge.",
    "Distill candidate opportunities from ingested artifacts, each with a provenance link and marked unvalidated.",
    "Reframe solution-shaped or business-shaped inputs into customer-need-shaped opportunities, or hold them for human review.",
    "Keep opportunities laddered up to the outcome and propose (not silently impose) opportunity-space structure.",
    "Append multiple unvalidated candidate solutions under a target opportunity for compare-and-contrast.",
    "Make each solution's underlying assumptions explicit as #Assumption nodes beneath it — one belief per node, stated so it could be false — and propose (never run) an assumption test beneath each. A test attaches under the assumption it probes, not under the solution.",
    "Finish a solution by appending its definition of done to the end of the solution node: the AssumptionTest's title in PLAIN QUOTED TEXT on its own line — \"Some test title\", never `[[Some test title]]` — and beneath it the one command that will go green when the solution is built. A builder reads the solution, not the layer beneath it, and a definition of done kept one node away is a definition of done nobody reads. It is quoted rather than linked because a title is wikilinked exactly ONCE in the whole vault, by its parent; see the one-backlink rule below.",
    "Flag tree-hygiene issues: staleness, orphan solutions, duplicates, mislabeled nodes, and unbacked validity claims.",
    "Preserve full provenance for every node it touches: '## History' is append-only and every removal writes the line that explains it.",
    "Resolve duplicates by merging them, not by annotating both. Two nodes making the same claim are a debt the tree pays on every future pass — each one re-read, re-counted, and re-ideated under. `ost_merge_nodes` folds one into the other, repoints every inbound edge, and deletes the loser's file; you choose the survivor and write the merged prose. Annotate instead only when you are unsure they are the same claim, and say what would settle it.",
    "Keep every wikilink on one line. A hard-wrapped paragraph that breaks a [[Node title]] across two lines produces bracketed text and no edge: it reads correctly in the source, and the graph — the artifact this whole thing produces — simply lacks the line. Let the line run long rather than wrap inside the brackets. `check` fails on it (rule wrapped-wikilink) and the hygiene pass reports it, because discipline alone has repeatedly not been enough.",
    "State a test's lane once, in one sentence, and let it name exactly one lane. `**Lane: compute-only.**` is a declaration a tool can read back; `**Lane: compute-only for the census, humans-required for the fixing.**` is two tests wearing one node, and the reader refuses it rather than picking a half. If a test really does split, split the test. A lane written in prose is still only a suggestion: `check` fails when it contradicts the `lane:` field (rule lane-conflict), and nothing ever promotes prose to a label — only a human's `ost-agent lane --set` moves what compute may run.",
    "Raise a flag or proposal for a human whenever an action is ambiguous or would generate/validate knowledge."
  ],
  "agentMustNot": [
    "Run interviews, experiments, or assumption tests, or record synthetic results as evidence.",
    "Write implementation code or build solutions.",
    "Invent, edit, or change the desired outcome (may only flag a mis-formed outcome as a question for humans).",
    "Remove or rewrite a '## Results', '## Uncovered' or '## Instrument Log' section. These record that something happened outside the tree — a human's finding, a stated limit, an observed exit code — and every gate reads one. Deleting one revokes a permit a human granted, which is the same act as authoring one. No tool can express it: an edit takes prose only, and a merge carries them across.",
    "Retract a node, or try to. A '## Retraction' takes a node out of EVERY read — no count, scan, gate, rollup or sweep returns it — while its file, its history and the retraction line all stay on disk, which is the only way back an append-only vault has. That makes it a delete in the one form no invariant can see, so it is a human's call on the CLI (`ost-agent retract \"<node>\" -b \"<who>\" -w \"<why>\"`) and the heading is refused in every argument you can pass. A merge cannot carry one across either. When a node should never have been written, say so and ask; to record that work stopped, use `deferred`.",
    "Rewrite a node's history. '## History' is append-only; a correction appends a new dated line rather than editing an old one.",
    "Mark any opportunity, solution, or assumption as validated or confirmed.",
    "Auto-select a target opportunity or declare a winning solution.",
    "Phrase an opportunity as a solution, feature, or business metric.",
    "Silently re-architect the tree without proposing the change for human confirmation."
  ],
  "obsidianFormat": {
    "nodeFile": "One Markdown file per node; the filename minus .md is the node title. Filenames must be filesystem-safe (no / \\ : * ? etc.) and unique across the vault so wikilinks resolve by name.",
    "tagLine": "The first body line carries the layer tag: #Outcome, #Opportunity, #Solution, #Assumption, or #AssumptionTest. Graph view Groups bind one color per layer via a tag:#... query.",
    "wikilinks": "A parent->child edge is a [[Child Title]] wikilink written in the parent note (outgoing link); the child sees its parent via the Backlinks pane. The built-in Graph view's Display 'Arrows' toggle renders link direction natively, no plugin required. Keep every wikilink on a single line: a hard-wrapped paragraph that breaks one across two lines produces bracketed text and no edge, which reads correctly in the source and is missing from the graph. Let the line run long instead of wrapping inside the brackets. `check` fails on it (rule wrapped-wikilink) and the hygiene pass reports it, because discipline alone has not been enough.",
    "frontmatter": "YAML frontmatter carries type (outcome|opportunity|solution|assumption|assumption_test), status, source/provenance, created (ISO date), and confidence (high|medium|low). Frontmatter is the machine-readable source of truth for state; inline tags drive graph coloring. Keep type in frontmatter in sync with the body tag.",
    "unvalidatedMarking": "Agent-ideated, not-yet-validated nodes carry a companion #unvalidated tag on the same first body line (e.g. '#Solution #unvalidated') plus status: unvalidated in frontmatter; a dedicated Graph group query tag:#unvalidated colors them in a warning color. Status vocabulary (unvalidated -> in-discovery -> validated -> shipped -> deferred) is a vault/tooling convention, not Torres canon.",
    "provenance": "Every note ends with an append-only '## History' section of dated entries; existing lines are never edited or deleted, and every removal elsewhere in the note writes a dated line here saying what went and why. Corrections append a new entry and update frontmatter while leaving original provenance intact. A node's PROSE may be rewritten (ost_edit_node) and a duplicate may be folded into the node that survives and its file deleted (ost_merge_nodes) — git is the recovery path, and the merge commit names what it removed. What no tool can touch either way are the reserved sections '## Results', '## Uncovered', '## Instrument Log' and '## Retraction': an edit takes prose only and reattaches them verbatim, and a merge carries the loser's across onto the survivor — except a retraction, which no merge may carry, because copying one onto a live node would take that node out of every count and gate without anyone having retracted it. Abandoned nodes are still set status: deferred rather than merged away — deferred means 'not now', merged means 'this was the same claim'. A node that should never have been written at all is RETRACTED, and that is a human's call on the CLI (`ost-agent retract \"<node>\" -b \"<who>\" -w \"<why>\"`): a retracted node keeps its file, its history and the retraction line, and is returned by no read — no count, scan, gate, rollup or sweep — which is why the agent has no way to write one. Ask for it; do not attempt it. Renames are done inside Obsidian so inbound wikilinks auto-update."
  },
  "glossary": [
    {
      "term": "Opportunity Solution Tree (OST)",
      "definition": "A visual representation of the paths a team might take to reach a desired outcome, with four layers (outcome, opportunities, solutions, assumption tests) that keeps a team aligned and outcome-focused during continuous discovery."
    },
    {
      "term": "Outcome",
      "definition": "The single desired result at the root of the tree; ideally a product outcome (a customer behavior or sentiment in the product the team can influence), distinct from a business metric or an output."
    },
    {
      "term": "Product outcome",
      "definition": "A measure of a customer behavior in the product or a customer's sentiment about it, directly within the team's control and a leading indicator of business value; Torres's recommended scope for discovery."
    },
    {
      "term": "Business outcome",
      "definition": "A financial or lagging health metric (revenue, market share, churn) only indirectly influenced by a team's actions."
    },
    {
      "term": "Traction metric",
      "definition": "Adoption of a single feature; too narrow a scope to anchor discovery on its own."
    },
    {
      "term": "Opportunity",
      "definition": "An unmet customer need, pain point, or desire, phrased from the customer's perspective and sourced from interviews; addressable in more than one way (the litmus test that distinguishes it from a solution)."
    },
    {
      "term": "Solution",
      "definition": "A product, feature, service, workflow, process, documentation, or anything else offered to customers to address a known opportunity."
    },
    {
      "term": "Assumption test",
      "definition": "A small, fast test of a single underlying assumption a solution depends on, used to choose among solutions rather than validate a whole idea."
    },
    {
      "term": "Compare-and-contrast",
      "definition": "Evaluating multiple competing solutions against one another (which makes 'good' judgeable) instead of assessing a single idea in isolation."
    },
    {
      "term": "Opportunity sizing",
      "definition": "A qualitative estimate of how many customers an opportunity impacts and how often, used in prioritization; not a numeric scoring formula."
    },
    {
      "term": "Two-way-door decision",
      "definition": "Torres's framing for opportunity prioritization: a reversible, low-cost decision where moving fast beats waiting for perfect data."
    },
    {
      "term": "Continuous discovery",
      "definition": "At a minimum weekly touchpoints with customers by the team building the product, where they conduct small research activities in pursuit of a desired outcome."
    },
    {
      "term": "Generative vs. evaluative research",
      "definition": "Interviewing is generative (it discovers opportunities); assumption testing is evaluative (it evaluates solutions). Both require evidence from real people, which an automated maintainer cannot produce."
    }
  ],

  /**
   * Which of the server's tools the skill hands the model — and, for anything
   * held back, the reason, in the file the skill is generated from.
   *
   * This lives here rather than as a literal in `scripts/gen-skill.ts` because
   * a grant is a decision about what the agent may do, and decisions in this
   * repo live next to their argument. `test/skill/surface-parity.test.ts` reads
   * the rendered `SKILL.md` against `MCP_TOOL_NAMES` — never against this list —
   * so a tool added to the server surface and forgotten here fails the build
   * rather than becoming an invisible omission (readiness criterion **D3**).
   *
   * The bar for `grant: false` is deliberately high: the skill is what tells the
   * model to keep a tree honest, and a tool it does not name is a tool the model
   * will not reach for. An omission has to say what would go wrong if it were
   * granted, and that sentence is rendered into the skill as an HTML comment, so
   * the next reader finds it where they notice the absence.
   *
   * Notes on the six that were held back until 2026-07-30 and are now granted:
   *
   * - The four reporters (`ost_check`, `ost_debt`, `ost_status`, `ost_gate`) are
   *   read-only analyses that produce no diff at all. Withholding them left the
   *   skill instructing the model to keep the tree honest while denying it every
   *   tool that reports whether it is — the model could create a violation and
   *   had no way to look at the list of them.
   * - `ost_set_evidence` is already granted on `/ost-pass` (R7), and the write
   *   boundary refuses any rung above what the node's own sources earn (B3), so
   *   the skill grant reaches nothing the unattended surface does not already.
   * - `ost_flag_humans_required` is the sixth, and its argument is long enough to
   *   live at the entry itself.
   *
   * **Nothing is withheld today, and the machinery that would demand a reason is
   * still here on purpose.** `scripts/gen-skill.ts` renders an
   * `<!-- omitted: … -->` comment for every `grant: false`, and
   * `test/skill/surface-parity.test.ts` exercises that branch against
   * constructed skill text rather than against the real file — so the next
   * withholding has to argue itself in this list before it can ship, and cannot
   * arrive as a name that quietly is not there.
   *
   * **A skill grant is not a command grant, and the difference is load-bearing.**
   * `.claude/commands/*.md` are commands; this list renders `SKILL.md`, which is
   * a skill. `test/eval/clearability.test.ts` builds its `/ost-pass` column by
   * parsing `.claude/commands/ost-pass.md`'s frontmatter and nothing else, so
   * adding a tool here does not move a single cell of that table — and R7's
   * argument about what the unattended sweep can reach is untouched by anything
   * in this list. The next reader will assume otherwise; that is why this
   * paragraph is here.
   *
   * The comments below are the merits, per tool. `grant: true` entries that need
   * no argument beyond "the loop uses it" carry none.
   */
  "skillTools": [
    // The maintenance loop, in the order the loop runs them.
    { "name": "ost_ingest_inbox", "grant": true },
    { "name": "ost_next_work", "grant": true },
    { "name": "ost_read_tree", "grant": true },
    { "name": "ost_create_node", "grant": true },
    { "name": "ost_link_nodes", "grant": true },
    { "name": "ost_append_to_node", "grant": true },
    { "name": "ost_set_status", "grant": true },
    // Granted: `/ost-pass` already grants it (R7) and the write boundary refuses
    // a rung above what the node's sources earn (B3), so this adds no reach.
    // Labelling a pre-ladder node's believability is ordinary maintenance, and a
    // model that cannot say "assertion" leaves the rung silently wrong instead.
    { "name": "ost_set_evidence", "grant": true },
    // Granted. This is the tool that lets a pass go back and give a runnable
    // command to a test written before instruments existed — the 243 in this
    // product's own vault, every one of them a dead end for the builder. A skill
    // that named the requirement and withheld the only tool that satisfies it
    // would leave the model able to see the debt and unable to pay it.
    //
    // It reaches no gate on its own: a build permit needs an OBSERVED failure,
    // and only `ost-agent verify` — CLI, off every allowlist — can record one.
    { "name": "ost_set_instrument", "grant": true },
    { "name": "ost_annotate", "grant": true },
    // Granted together: the three that walked back append-only. A tree that may
    // only grow cannot resolve its own overlap — annotating two duplicates leaves
    // two nodes and adds a third claim, and every later pass re-reads both. This
    // product's own vault reached 566 nodes and a root of 89KB that way.
    //
    // The bound is what they cannot reach, not who calls them. An edit takes
    // PROSE, never a whole body; a merge carries the loser's reserved blocks onto
    // the survivor. So `## Results`, `## Uncovered` and `## Instrument Log` became
    // unremovable at the same moment bodies became rewritable — deleting a human's
    // recorded result is the same act as authoring one, and the surface now
    // refuses both directions.
    { "name": "ost_detach_nodes", "grant": true },
    { "name": "ost_edit_node", "grant": true },
    { "name": "ost_merge_nodes", "grant": true },
    // Outward sensing: read-only, metered against one shared per-pass budget.
    { "name": "ost_search_web", "grant": true },
    { "name": "ost_read_web", "grant": true },
    { "name": "ost_read_repo", "grant": true },
    { "name": "ost_rank_source", "grant": true },
    // The reporters. Read-only, no diff, no rung they can move. They exist so a
    // maintainer can read the tree's own health back; a skill that omits them
    // asks the model to keep the tree honest with its eyes shut.
    { "name": "ost_check", "grant": true },
    { "name": "ost_debt", "grant": true },
    { "name": "ost_status", "grant": true },
    { "name": "ost_gate", "grant": true },
    // Granted 2026-07-30, on a condition that was checked rather than assumed.
    //
    // It was withheld for one day, and the withholding named its own expiry:
    // `flagHumansRequired` used to write the label unconditionally, so filing
    // the flag against a test whose own prose already claimed a different lane
    // left a `lane-conflict` nothing on this surface could clear — a safety tool
    // whose correct use turns permanently red is a safety tool that gets routed
    // around, and the way a model routes around this one is by never flagging.
    // R2 closed that at the boundary (`src/ost/lanes.ts`: the flag refuses when
    // the node's own prose names another lane), and the condition written into
    // the withholding was that `test/eval/clearability.test.ts` pin the refusal
    // green. It does: the `lane-conflict` row now reads `create: false` on the
    // **mcp** surface — which is `MCP_TOOL_NAMES` entire, this tool included —
    // and pins the refusal's text, so removing the guard fails that row rather
    // than quietly re-opening this one.
    //
    // Two-call authorship was probed before flipping, because that table is
    // explicit that a `false` cell means "the declared single attempt failed",
    // not "no sequence could". Flag first, then append a contradicting
    // declaration: the flag's own History entry introduces a `## ` heading, and
    // `ownProse` stops at the first one, so nothing appended afterwards can ever
    // become the node's own claim. Prose first, then flag: refused. Both
    // orderings are covered by `test/skill/surface-parity.test.ts`'s note and by
    // R2's row; neither leaves a wedge behind.
    //
    // What is NOT changed by this line: `/ost-pass`'s grant. R7's containment
    // argument reads `.claude/commands/ost-pass.md`, the tool is still absent
    // from it, and `test/skill/surface-parity.test.ts` pins that absence so this
    // grant cannot drift into the unattended sweep by association.
    { "name": "ost_flag_humans_required", "grant": true }
  ]
} as const;

export type OstRuleset = typeof OST_RULESET;
