/**
 * OST_RULESET — machine-usable rules distilled from Teresa Torres's Opportunity
 * Solution Tree methodology (Continuous Discovery Habits, 2021).
 *
 * Generated by the ost-research workflow (adversarially verified per dimension) and
 * consumed by the discovery processes' system prompts and definition-of-done checks.
 * The prose companion is docs/reference/teresa-torres-ost.md. Edit deliberately —
 * changing a rule changes agent behavior.
 */

export const OST_RULESET = {
  "layers": [
    {
      "tag": "#Outcome",
      "name": "Outcome",
      "definition": "The single desired outcome at the root that scopes all discovery; should be a product outcome (a customer behavior in the product or sentiment about it, within the team's control), not a business/financial metric or an output like 'ship feature X'.",
      "role": "Root; one per tree; assigned by leadership, never invented or changed by the agent."
    },
    {
      "tag": "#Opportunity",
      "name": "Opportunity",
      "definition": "An unmet customer need, pain point, or desire, phrased from the customer's perspective and sourced from customer interviews; never a solution or feature. Opportunities nest into a multi-level sub-tree (an opportunity can parent other opportunities).",
      "role": "Customer-value layer connecting the outcome to solutions; siblings are distinct alternatives, parent-child pairs are subset relationships."
    },
    {
      "tag": "#Solution",
      "name": "Solution",
      "definition": "A product, feature, service, workflow, process, documentation, or anything else offered to address a known opportunity. Attaches to the single target opportunity it addresses.",
      "role": "Candidate to be compared and de-risked; generate multiple per target opportunity; enters the tree unvalidated."
    },
    {
      "tag": "#AssumptionTest",
      "name": "Assumption test",
      "definition": "A small, fast test of a single underlying assumption a solution depends on (desirability, viability, feasibility, or usability), used to choose among solutions rather than validate one whole idea.",
      "role": "Bottom layer; attaches beneath the specific solution whose assumption it probes; proposed by the agent, run only by humans."
    }
  ],
  "treeRules": [
    "Exactly one desired outcome sits at the root; multiple outcomes mean multiple trees.",
    "The tree flows strictly downward: Outcome -> Opportunities (nested) -> Solutions -> Assumption Tests, with each node mapping to its parent.",
    "Place each node under its single best-fit parent; if an opportunity plausibly fits two parents, flag for human review rather than duplicating or double-linking.",
    "Opportunities form a multi-level sub-tree: an opportunity node may be the parent of other opportunity nodes; the tree is not four flat levels.",
    "Parent-child opportunity relationships represent subsets; sibling relationships represent distinct alternatives at the same level.",
    "Every solution must address at least one opportunity in the tree; no orphan solutions.",
    "Every assumption test must map to exactly one specific solution.",
    "Sibling opportunities should be distinct from one another; the tree is deliberately incomplete and evolving, and siblings need not be collectively exhaustive.",
    "The tree is a living artifact: when evidence invalidates a branch, re-chart it (evolve the solution, pick a different opportunity, or flag the outcome) rather than discarding the rest of the tree."
  ],
  "opportunityRules": [
    "State every opportunity as an unmet customer need, pain point, or desire from the customer's perspective, never as a solution, feature, or business ask.",
    "Apply the litmus test 'Is there more than one way to address this opportunity?': if only one implementation fits, it is a solution in disguise and belongs one layer down or must be reframed upward into the underlying need.",
    "Source opportunities from story-based, past-behavior customer interviews rather than internal brainstorming.",
    "Derive top-level opportunities from key moments in a customer experience map, then nest sub-opportunities under the relevant parent.",
    "Reframe solution-shaped or business-shaped inputs into need-shaped opportunities, or hold them for human review; never assert them as validated needs.",
    "Attach every opportunity so it ladders up to the desired outcome."
  ],
  "solutionRules": [
    "Attach each solution to the single target opportunity it addresses.",
    "Generate multiple competing solutions per target opportunity (aim for at least three) and narrow to a consideration set.",
    "Compare and contrast solutions against each other rather than validating a single idea in isolation ('good' is judgeable only relative to alternatives).",
    "Prefer generating more solutions especially when there is risk, when the opportunity is a differentiator, or when innovation is needed.",
    "Target one opportunity at a time (a work-in-progress limit) and go deep before moving on.",
    "Every agent-originated solution enters the tree unvalidated; the agent never promotes or declares a winning solution."
  ],
  "assumptionCategories": [
    "desirability",
    "viability",
    "feasibility",
    "usability"
  ],
  "assumptionRules": [
    "Surface the underlying assumptions a solution depends on and test the riskiest ones, rather than testing the whole solution.",
    "Classify each assumption into one of the four risk categories: desirability, viability, feasibility, or usability (also consider potential-harm/ethical assumptions as an additional check).",
    "Keep each test small and fast, with a success threshold pre-committed before running.",
    "Use assumption-test results as comparative evidence to choose among solutions, not as a yes/no verdict on one idea.",
    "The agent may propose test designs but must never run tests or record test results as evidence; humans run tests with real customers/data."
  ],
  "prioritization": [
    "Prioritize opportunities, not solutions; the strategic decision is which customer need to target.",
    "Prioritize row by row: assess top-level opportunities, pick the top branch, then drill into that branch's children.",
    "Assess opportunity sizing qualitatively (how many customers are impacted, and how often), not with a multiplicative reach x frequency formula.",
    "Weigh customer factors (importance to customers), market factors (effect on market position), and company factors (fit with vision, mission, and strategy).",
    "Estimate how much impact addressing each opportunity would have on the desired outcome.",
    "Do not use quantified scoring formulas (e.g. RICE); treat prioritization as messy, subjective, reversible two-way-door decisions where speed beats false precision.",
    "Opportunity and solution selection are human decisions; the agent may surface sizing information but must not auto-select a target opportunity or a winning solution."
  ],
  "cadence": [
    "Continuous discovery means at a minimum weekly touchpoints with customers by the team building the product, where they conduct small research activities toward a desired outcome.",
    "Work one outcome (one tree) at a time.",
    "Conduct weekly story-based customer interviews to source and refine opportunities from real unmet needs.",
    "Map and structure the opportunity space, then prioritize opportunities row by row and select a single target opportunity at a time.",
    "Generate multiple solutions for the target opportunity, then run small, fast assumption tests continuously instead of one big up-front validation.",
    "Update the tree as interviews and tests land, and revisit or re-chart a branch when evidence invalidates it."
  ],
  "agentMust": [
    "Treat itself as a cartographer of the team's knowledge: organize, represent, and question, but never generate or validate knowledge.",
    "Distill candidate opportunities from ingested artifacts, each with a provenance link and marked unvalidated.",
    "Reframe solution-shaped or business-shaped inputs into customer-need-shaped opportunities, or hold them for human review.",
    "Keep opportunities laddered up to the outcome and propose (not silently impose) opportunity-space structure.",
    "Append multiple unvalidated candidate solutions under a target opportunity for compare-and-contrast.",
    "Make each solution's underlying assumptions explicit and propose (never run) assumption tests.",
    "Flag tree-hygiene issues: staleness, orphan solutions, duplicates, mislabeled nodes, and unbacked validity claims.",
    "Preserve full provenance and append-only history for every node it touches.",
    "Raise a flag or proposal for a human whenever an action is ambiguous or would generate/validate knowledge."
  ],
  "agentMustNot": [
    "Run interviews, experiments, or assumption tests, or record synthetic results as evidence.",
    "Write implementation code or build solutions.",
    "Invent, edit, or change the desired outcome (may only flag a mis-formed outcome as a question for humans).",
    "Delete or overwrite existing nodes or history; append, annotate, mark-stale, or propose-for-archive instead.",
    "Mark any opportunity, solution, or assumption as validated or confirmed.",
    "Auto-select a target opportunity or declare a winning solution.",
    "Phrase an opportunity as a solution, feature, or business metric.",
    "Silently re-architect the tree without proposing the change for human confirmation."
  ],
  "obsidianFormat": {
    "nodeFile": "One Markdown file per node; the filename minus .md is the node title. Filenames must be filesystem-safe (no / \\ : * ? etc.) and unique across the vault so wikilinks resolve by name.",
    "tagLine": "The first body line carries the layer tag: #Outcome, #Opportunity, #Solution, or #AssumptionTest. Graph view Groups bind one color per layer via a tag:#... query.",
    "wikilinks": "A parent->child edge is a [[Child Title]] wikilink written in the parent note (outgoing link); the child sees its parent via the Backlinks pane. The built-in Graph view's Display 'Arrows' toggle renders link direction natively, no plugin required.",
    "frontmatter": "YAML frontmatter carries type (outcome|opportunity|solution|assumption_test), status, source/provenance, created (ISO date), and confidence (high|medium|low). Frontmatter is the machine-readable source of truth for state; inline tags drive graph coloring. Keep type in frontmatter in sync with the body tag.",
    "unvalidatedMarking": "Agent-ideated, not-yet-validated nodes carry a companion #unvalidated tag on the same first body line (e.g. '#Solution #unvalidated') plus status: unvalidated in frontmatter; a dedicated Graph group query tag:#unvalidated colors them in a warning color. Status vocabulary (unvalidated -> in-discovery -> validated -> shipped -> deferred) is a vault/tooling convention, not Torres canon.",
    "provenance": "Every note ends with an append-only '## History' section of dated entries; existing lines are never edited or deleted. Corrections append a new entry and update frontmatter while leaving original provenance intact. Abandoned nodes are set status: deferred (or superseded via a wikilink), never deleted; renames are done inside Obsidian so inbound wikilinks auto-update."
  },
  "glossary": [
    {
      "term": "Opportunity Solution Tree (OST)",
      "definition": "A visual representation of the paths a team might take to reach a desired outcome, with four layers (outcome, opportunities, solutions, assumption tests) that keeps a team aligned and outcome-focused during continuous discovery."
    },
    {
      "term": "Outcome",
      "definition": "The single desired result at the root of the tree; ideally a product outcome (a customer behavior or sentiment in the product the team can influence), distinct from a business metric or an output."
    },
    {
      "term": "Product outcome",
      "definition": "A measure of a customer behavior in the product or a customer's sentiment about it, directly within the team's control and a leading indicator of business value; Torres's recommended scope for discovery."
    },
    {
      "term": "Business outcome",
      "definition": "A financial or lagging health metric (revenue, market share, churn) only indirectly influenced by a team's actions."
    },
    {
      "term": "Traction metric",
      "definition": "Adoption of a single feature; too narrow a scope to anchor discovery on its own."
    },
    {
      "term": "Opportunity",
      "definition": "An unmet customer need, pain point, or desire, phrased from the customer's perspective and sourced from interviews; addressable in more than one way (the litmus test that distinguishes it from a solution)."
    },
    {
      "term": "Solution",
      "definition": "A product, feature, service, workflow, process, documentation, or anything else offered to customers to address a known opportunity."
    },
    {
      "term": "Assumption test",
      "definition": "A small, fast test of a single underlying assumption a solution depends on, used to choose among solutions rather than validate a whole idea."
    },
    {
      "term": "Compare-and-contrast",
      "definition": "Evaluating multiple competing solutions against one another (which makes 'good' judgeable) instead of assessing a single idea in isolation."
    },
    {
      "term": "Opportunity sizing",
      "definition": "A qualitative estimate of how many customers an opportunity impacts and how often, used in prioritization; not a numeric scoring formula."
    },
    {
      "term": "Two-way-door decision",
      "definition": "Torres's framing for opportunity prioritization: a reversible, low-cost decision where moving fast beats waiting for perfect data."
    },
    {
      "term": "Continuous discovery",
      "definition": "At a minimum weekly touchpoints with customers by the team building the product, where they conduct small research activities in pursuit of a desired outcome."
    },
    {
      "term": "Generative vs. evaluative research",
      "definition": "Interviewing is generative (it discovers opportunities); assumption testing is evaluative (it evaluates solutions). Both require evidence from real people, which an automated maintainer cannot produce."
    }
  ]
} as const;

export type OstRuleset = typeof OST_RULESET;
