/**
 * The capability manifest: the exact surface the shipped artefact exposes,
 * written down beside it and bound to its bytes, so a skeptical operator can
 * check the claim instead of believing it.
 *
 * The need is recorded in the meta vault as "Want proof no hijackable capability
 * even exists". The repository already makes that claim true — `ALLOWED_TOOL_NAMES`
 * is closed, `assertNoDestructiveTool` fails closed, and `MCP_TOOL_NAMES` decides
 * what a session may call. What it does not do is make the claim *checkable* by
 * anyone who has not read the source. An operator deciding whether to leave this
 * running unattended has the plugin directory in front of them and a README that
 * asserts a property. This module is the difference between those two states.
 *
 * ## Three properties, and only the first two are ours to give
 *
 * 1. **Enumeration.** The manifest lists every capability the artefact exposes —
 *    each MCP tool a session can call and each CLI subcommand the binary answers
 *    to — with a fingerprint over the shape of its arguments. A tool that grew a
 *    parameter is a different capability from the one that was audited, and a
 *    manifest that recorded only names would call them the same.
 *
 * 2. **Binding.** The manifest names the artefact by SHA-256 over its bytes. That
 *    is what makes it a statement about the *running* binary rather than about
 *    the source it was supposedly built from: an operator with `shasum` and no
 *    Node.js at all can confirm the file they are about to launch is the file the
 *    list describes, and {@link verifyRelease} refuses a manifest whose digest has
 *    drifted from the artefact beside it.
 *
 * 3. **Authenticity.** A digest binds the manifest to the artefact; it does not
 *    say who wrote either. That takes a signature over the manifest by a key an
 *    operator trusts, and a key is the one input compute cannot manufacture for
 *    itself — a private key generated by this process, committed to this
 *    repository, would let anyone who can clone it re-sign a rewritten manifest,
 *    which is worse than being unsigned because it looks signed. So the mechanism
 *    is here, complete and tested, and the custody is a human's:
 *    {@link signManifest} takes a key the maintainer holds and
 *    {@link verifyRelease} enforces the signature the moment a trusted public key
 *    is published. Until one is, the shipped manifest is integrity-bound and
 *    unauthenticated, and {@link ReleaseVerdict.authenticity} says so out loud
 *    rather than letting a reader assume the stronger property.
 *
 * ## What a green verdict does not mean
 *
 * The surface is observed by *running the artefact and asking it* — spawning
 * `mcp` and reading `tools/list`, spawning `--help` and reading the subcommand
 * table (see `capability-surface.ts`). An artefact that lies about itself lies to
 * this check too, so nothing here defends against a malicious build; what it
 * defends against is the failure that actually happens, which is a surface that
 * grew a capability nobody wrote down. The defence against a malicious build is
 * property 3, and property 3 is waiting on a key.
 *
 * Everything in this file is a pure function over data. The spawning lives in
 * `capability-surface.ts` and the file reading in `scripts/gen-capability-manifest.ts`,
 * so the decision — *does this release ship?* — is testable without a build.
 */
import { createHash, createPublicKey, sign as cryptoSign, verify as cryptoVerify, type KeyLike, type KeyObject } from "node:crypto";

/** The manifest format, versioned so a reader can refuse one it does not understand. */
export const MANIFEST_SCHEMA = "ost-agent/capability-manifest@1";

/** Where the manifest and the artefact it describes live, relative to the repository root. */
export const MANIFEST_PATH = "dist/capability-manifest.json";
/** The artefact the plugin launches, and therefore the one a manifest has to be about. */
export const ARTIFACT_PATH = "dist/ost-agent.mjs";
/**
 * Where a published release key is looked for.
 *
 * A key committed beside the artefact it signs is a pin, not a root of trust:
 * whoever can rewrite the artefact can rewrite the key. Its value is that an
 * operator who obtained the maintainer's key out of band can diff this file
 * against it once, and every later release is then checked against a key they
 * chose. {@link verifyRelease} therefore takes the trusted key as an argument —
 * this path is only the default an operator may accept or replace.
 */
export const RELEASE_KEY_PATH = ".claude-plugin/release-key.pub";

/** Which surface a capability is reachable through. Both are the agent; neither is private. */
export type CapabilitySurface = "mcp-tool" | "cli-command";

/** One thing the artefact can be asked to do. */
export interface Capability {
  /** The name a caller uses: an MCP tool name, or a CLI subcommand. */
  readonly name: string;
  readonly surface: CapabilitySurface;
  /**
   * SHA-256 over the argument shape the artefact reported for this capability —
   * the canonicalised JSON input schema for a tool, the usage string for a
   * subcommand. Two capabilities with the same name and different fingerprints
   * are different capabilities, and the release must not call them the same.
   */
  readonly fingerprint: string;
}

/** The artefact a manifest is about, named by content rather than by path alone. */
export interface ArtifactIdentity {
  readonly path: string;
  readonly bytes: number;
  readonly sha256: string;
}

/** A detached signature over {@link canonicalManifest}'s bytes. */
export interface ManifestSignature {
  readonly algorithm: "ed25519";
  /** SPKI DER, base64 — the public half, so a verdict can name the key it used. */
  readonly publicKey: string;
  /** The signature itself, base64. */
  readonly value: string;
}

/** Everything that is signed. A field added here changes what a signature covers. */
export interface ManifestBody {
  readonly schema: typeof MANIFEST_SCHEMA;
  /** The release this artefact belongs to — `package.json`'s version. */
  readonly version: string;
  readonly artifact: ArtifactIdentity;
  readonly capabilities: readonly Capability[];
}

/** The file on disk: the signed body, plus the signature when a key exists to make one. */
export interface CapabilityManifest extends ManifestBody {
  /** `null` — never absent — so an unsigned release is a stated fact rather than a missing field. */
  readonly signature: ManifestSignature | null;
}

/** Why a release must not ship. Each names the drift a reader would otherwise have to find. */
export type ReleaseFailure =
  | { readonly kind: "schema-unknown"; readonly found: string }
  | { readonly kind: "artifact-digest-mismatch"; readonly declared: string; readonly actual: string }
  | { readonly kind: "artifact-size-mismatch"; readonly declared: number; readonly actual: number }
  | { readonly kind: "version-mismatch"; readonly declared: string; readonly actual: string }
  /** The artefact exposes something the manifest never mentions — the dangerous direction. */
  | { readonly kind: "capability-undeclared"; readonly name: string; readonly surface: CapabilitySurface }
  /** The manifest claims a capability the artefact does not answer to. */
  | { readonly kind: "capability-absent"; readonly name: string; readonly surface: CapabilitySurface }
  /** Same name, different argument shape: audited as one thing, shipping as another. */
  | { readonly kind: "capability-changed"; readonly name: string; readonly surface: CapabilitySurface; readonly declared: string; readonly actual: string }
  | { readonly kind: "signature-missing"; readonly trustedKey: string }
  | { readonly kind: "signature-invalid" }
  | { readonly kind: "signature-untrusted-key"; readonly signedBy: string; readonly trustedKey: string };

/** How much of the manifest an operator may rely on. */
export type Authenticity =
  /** Signed, and the signature verifies against a key the caller named as trusted. */
  | "trusted"
  /** Signed and internally consistent, but nobody said the key is the right one. */
  | "self-signed"
  /** No signature. The manifest is bound to the artefact and attributed to no one. */
  | "unsigned";

export interface ReleaseVerdict {
  /** May this build ship? False on any failure — there is no advisory failure here. */
  readonly ok: boolean;
  readonly authenticity: Authenticity;
  readonly failures: readonly ReleaseFailure[];
}

/**
 * The exact bytes a signature covers.
 *
 * Hand-rolled rather than `JSON.stringify(body)` because a signature over a
 * serialisation whose key order is decided by whoever built the object is a
 * signature that fails for reasons unrelated to trust. Keys are emitted in a
 * fixed order at every level and capabilities are sorted, so two processes that
 * agree about the release agree about the bytes.
 */
export function canonicalManifest(body: ManifestBody): string {
  const capabilities = [...body.capabilities]
    .sort((a, b) => (a.surface === b.surface ? a.name.localeCompare(b.name) : a.surface.localeCompare(b.surface)))
    .map((c) => ({ name: c.name, surface: c.surface, fingerprint: c.fingerprint }));
  return JSON.stringify({
    schema: body.schema,
    version: body.version,
    artifact: { path: body.artifact.path, bytes: body.artifact.bytes, sha256: body.artifact.sha256 },
    capabilities,
  });
}

/** SHA-256, hex — the one digest this module speaks, for artefacts and fingerprints alike. */
export function sha256(data: Buffer | string): string {
  return createHash("sha256").update(data).digest("hex");
}

/**
 * The fingerprint of one capability's argument shape.
 *
 * Objects are canonicalised by sorting keys at every level, for the reason
 * {@link canonicalManifest} gives: a schema that serialises differently on two
 * machines would report a capability as changed when nothing changed, and a
 * fingerprint that cries wolf is one somebody removes.
 */
export function fingerprintOf(shape: unknown): string {
  return sha256(stableStringify(shape));
}

function stableStringify(value: unknown): string {
  if (value === null || typeof value !== "object") return JSON.stringify(value) ?? "null";
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`;
  const entries = Object.entries(value as Record<string, unknown>)
    .filter(([, v]) => v !== undefined)
    .sort(([a], [b]) => a.localeCompare(b));
  return `{${entries.map(([k, v]) => `${JSON.stringify(k)}:${stableStringify(v)}`).join(",")}}`;
}

/**
 * Sign a manifest body with a release key.
 *
 * Ed25519 because the operational question is "can a person check this on a
 * machine with nothing installed" — a 64-byte signature and a 44-character
 * public key fit in a README, and `node:crypto` verifies them with no argument
 * beyond the key. The key never comes from this repository: the caller reads it
 * from wherever the maintainer keeps it, and every path that could have created
 * one here is deliberately absent (see the module note on custody).
 */
export function signManifest(body: ManifestBody, privateKey: KeyLike): ManifestSignature {
  const value = cryptoSign(null, Buffer.from(canonicalManifest(body), "utf8"), privateKey).toString("base64");
  return { algorithm: "ed25519", publicKey: publicKeyOf(privateKey), value };
}

/**
 * The base64 SPKI DER of a key's public half — the form a manifest and a `.pub`
 * file both carry.
 *
 * Takes either half, because both callers are real: the generator has the
 * private key and needs the public one to report who signed, and an operator
 * has only the public key and needs it in the same encoding to compare. Node
 * throws rather than no-ops when `createPublicKey` is handed a key that is
 * already public, so the already-public case is answered directly.
 */
export function publicKeyOf(key: KeyLike): string {
  const isPublic = typeof key === "object" && key !== null && (key as KeyObject).type === "public";
  const publicKey = isPublic ? (key as KeyObject) : createPublicKey(key as never);
  return publicKey.export({ type: "spki", format: "der" }).toString("base64");
}

/** True if `signature` was made over `body` by the key it names. Never throws on malformed input. */
export function signatureVerifies(body: ManifestBody, signature: ManifestSignature): boolean {
  if (signature.algorithm !== "ed25519") return false;
  try {
    const key = createPublicKey({ key: Buffer.from(signature.publicKey, "base64"), format: "der", type: "spki" });
    return cryptoVerify(null, Buffer.from(canonicalManifest(body), "utf8"), key, Buffer.from(signature.value, "base64"));
  } catch {
    // A key or signature that will not even parse is an invalid signature, not a
    // crash: this runs inside a release gate, and a gate that throws where it
    // should refuse is a gate somebody wraps in a try/catch that swallows both.
    return false;
  }
}

export interface ReleaseInput {
  readonly manifest: CapabilityManifest;
  /** The artefact's bytes, as the operator would read them off disk. */
  readonly artifact: Buffer;
  /** What the artefact answered when asked what it exposes. */
  readonly observed: readonly Capability[];
  /** The release version the repository claims — `package.json`. */
  readonly version: string;
  /**
   * The key the caller trusts, base64 SPKI DER. Supplying one turns the
   * signature from a nice-to-have into a requirement: a release that cannot be
   * verified against it does not ship.
   */
  readonly trustedPublicKey?: string;
}

/**
 * Does this build ship?
 *
 * The whole decision, as one pure function over the four things an operator can
 * hold in their hands: the manifest, the artefact, what the artefact said about
 * itself, and — if they have one — the key they trust. Every failure is fatal.
 * There is no severity dial here on purpose: a manifest that is wrong in any of
 * these ways is a manifest a reader would be misled by, and "ships with a
 * warning" is how a warning becomes the normal state of the file.
 */
export function verifyRelease(input: ReleaseInput): ReleaseVerdict {
  const { manifest, artifact, observed, version, trustedPublicKey } = input;
  const failures: ReleaseFailure[] = [];

  if (manifest.schema !== MANIFEST_SCHEMA) failures.push({ kind: "schema-unknown", found: String(manifest.schema) });

  const actualDigest = sha256(artifact);
  if (manifest.artifact.sha256 !== actualDigest) {
    failures.push({ kind: "artifact-digest-mismatch", declared: manifest.artifact.sha256, actual: actualDigest });
  }
  if (manifest.artifact.bytes !== artifact.byteLength) {
    failures.push({ kind: "artifact-size-mismatch", declared: manifest.artifact.bytes, actual: artifact.byteLength });
  }
  if (manifest.version !== version) {
    failures.push({ kind: "version-mismatch", declared: manifest.version, actual: version });
  }

  failures.push(...surfaceDivergence(manifest.capabilities, observed));

  const authenticity = judgeAuthenticity(manifest, trustedPublicKey, failures);
  return { ok: failures.length === 0, authenticity, failures };
}

/**
 * Every way the declared surface and the observed one disagree.
 *
 * Both directions, because they fail differently and only one of them is loud.
 * A capability the manifest claims and the artefact does not have is an
 * embarrassment. A capability the artefact has and the manifest never mentions
 * is the thing the operator was promised could not happen — it is how a tool
 * added to `MCP_TOOL_NAMES` in a hurry reaches an unattended session while the
 * published list still reads the way it did when someone audited it.
 */
export function surfaceDivergence(
  declared: readonly Capability[],
  observed: readonly Capability[],
): ReleaseFailure[] {
  const key = (c: Capability) => `${c.surface} ${c.name}`;
  const declaredBy = new Map(declared.map((c) => [key(c), c]));
  const observedBy = new Map(observed.map((c) => [key(c), c]));
  const failures: ReleaseFailure[] = [];

  for (const c of observed) {
    const match = declaredBy.get(key(c));
    if (!match) {
      failures.push({ kind: "capability-undeclared", name: c.name, surface: c.surface });
    } else if (match.fingerprint !== c.fingerprint) {
      failures.push({
        kind: "capability-changed",
        name: c.name,
        surface: c.surface,
        declared: match.fingerprint,
        actual: c.fingerprint,
      });
    }
  }
  for (const c of declared) {
    if (!observedBy.has(key(c))) failures.push({ kind: "capability-absent", name: c.name, surface: c.surface });
  }
  return failures;
}

/** How much the signature is worth, and what it costs the verdict when a trusted key is named. */
function judgeAuthenticity(
  manifest: CapabilityManifest,
  trustedPublicKey: string | undefined,
  failures: ReleaseFailure[],
): Authenticity {
  const signature = manifest.signature;
  if (!signature) {
    // Unsigned is a stated position, not a failure — until an operator names a
    // key, at which point an unsigned build is exactly what they asked to be
    // protected from.
    if (trustedPublicKey) failures.push({ kind: "signature-missing", trustedKey: trustedPublicKey });
    return "unsigned";
  }
  if (!signatureVerifies(manifest, signature)) {
    failures.push({ kind: "signature-invalid" });
    return "unsigned";
  }
  if (!trustedPublicKey) return "self-signed";
  if (trustedPublicKey.trim() !== signature.publicKey) {
    failures.push({ kind: "signature-untrusted-key", signedBy: signature.publicKey, trustedKey: trustedPublicKey.trim() });
    return "self-signed";
  }
  return "trusted";
}

/** One line per failure, in the shape a person reading a red gate needs. */
export function explainFailure(f: ReleaseFailure): string {
  switch (f.kind) {
    case "schema-unknown":
      return `manifest schema "${f.found}" is not ${MANIFEST_SCHEMA} — this reader cannot judge it`;
    case "artifact-digest-mismatch":
      return `the manifest describes an artefact with sha256 ${f.declared}, but the one beside it hashes to ${f.actual} — regenerate the manifest`;
    case "artifact-size-mismatch":
      return `the manifest declares ${f.declared} bytes, the artefact is ${f.actual}`;
    case "version-mismatch":
      return `the manifest is for version ${f.declared}, the repository is at ${f.actual}`;
    case "capability-undeclared":
      return `the artefact exposes ${f.surface} "${f.name}" and the manifest does not list it — the published capability list is smaller than the real one`;
    case "capability-absent":
      return `the manifest lists ${f.surface} "${f.name}" and the artefact does not answer to it`;
    case "capability-changed":
      return `${f.surface} "${f.name}" has a different argument shape than the manifest records (${f.declared.slice(0, 12)} → ${f.actual.slice(0, 12)})`;
    case "signature-missing":
      return `a trusted release key is published (${f.trustedKey.slice(0, 16)}…) and this manifest carries no signature`;
    case "signature-invalid":
      return "the manifest's signature does not verify against the key it names";
    case "signature-untrusted-key":
      return `the manifest is signed by ${f.signedBy.slice(0, 16)}… and the trusted key is ${f.trustedKey.slice(0, 16)}…`;
  }
}

/** The verdict as an operator sees it: the headline, then one line per failure. */
export function renderVerdict(verdict: ReleaseVerdict, manifest: CapabilityManifest): string {
  const tools = manifest.capabilities.filter((c) => c.surface === "mcp-tool").length;
  const commands = manifest.capabilities.filter((c) => c.surface === "cli-command").length;
  const lines = [
    `${verdict.ok ? "MATCHES" : "DIVERGED"} — ${manifest.artifact.path} @ ${manifest.version}`,
    `  ${tools} tool(s), ${commands} command(s) declared; artefact sha256 ${manifest.artifact.sha256}`,
    `  authenticity: ${authenticityLine(verdict.authenticity)}`,
  ];
  for (const f of verdict.failures) lines.push(`  ✗ ${explainFailure(f)}`);
  return lines.join("\n");
}

function authenticityLine(a: Authenticity): string {
  switch (a) {
    case "trusted":
      return "trusted — signed by the key you named";
    case "self-signed":
      return "self-signed — the signature is internally consistent; nothing here says the key is the right one";
    case "unsigned":
      return `unsigned — bound to the artefact by digest and attributed to no one (no key at ${RELEASE_KEY_PATH})`;
  }
}
