/**
 * Three routes through one branch, at three risk levels, each stating what
 * taking it forecloses.
 *
 * This is the mechanism of the tree node "Offer three routes at different risk
 * levels and say what each one forecloses". A single recommended path hides the
 * assumption that makes it efficient; three routes make that assumption an
 * explicit choice, which is the difference between advice and a decision. The
 * operator picks, and picks knowing the price of being wrong.
 *
 * **The node's own objection is the design constraint here, and it is worth
 * quoting: this is "the option most likely to be generated by a model with no
 * real basis for the risk levels it assigns — in which case the operator is
 * choosing between three fictions with a confident frame around them."** So
 * nothing in this file is written by a model and nothing is stamped:
 *
 *   - **The risk level is derived, never asserted.** {@link riskOf} reads it off
 *     the route's own step list — how much of the branch the route commits
 *     before it learns anything. A route that builds first is `high` because it
 *     builds first, not because someone labelled it so. There is no parameter
 *     anywhere that lets a caller set a route's risk.
 *   - **Every foreclosure names a real node in the branch.** A `forecloses`
 *     entry carries the title it forecloses on, resolved from the tree, so the
 *     trade-off can be checked rather than admired. Prose with no target is not
 *     expressible.
 *   - **Three routes that do not genuinely differ are refused, not padded.** The
 *     node names the failure mode itself — "if two of them are obviously worse
 *     the whole thing is a recommendation wearing a costume". A branch too thin
 *     to support three distinct trade-offs comes back as {@link ThinBranch},
 *     saying which route it could not build and what would make it possible.
 *     That refusal is a finding about the tree, and it is far more common than
 *     the node's framing implies: most branches carry one buildable solution or
 *     one live belief, and one of anything cannot be routed around.
 *
 * The three routes are the node's own three, and each one is assembled from what
 * the branch actually holds:
 *
 *   - `learn-first` — run every unrun test before building anything. Forecloses
 *     the live build permits it defers, and the measurements it spends on
 *     beliefs that a failure of the riskiest one would have made moot.
 *   - `riskiest-belief-first` — test the single belief whose failure kills the
 *     most of the branch, then decide. Forecloses the same deferred permits, and
 *     every other belief it leaves unmeasured while that one test runs.
 *   - `commit-early` — build the first buildable solution now. Forecloses the
 *     clean read on every test beneath it (a reading taken on a thing already
 *     paid for is not the reading the test was designed to produce), and the
 *     comparison against the buildable siblings it does not build.
 *
 * What a green here does not settle, and the assumption test above this says so
 * itself: whether a reader who is shown the three with the labels stripped ranks
 * them the way this module ranked them. That needs a reader, and it stays with a
 * human. Compute can guarantee three routes exist, differ, and each name what it
 * costs; it cannot check that the ranking is right.
 */
import { buildPermit } from "../eval/buildable.js";
import { hasRecordedResult } from "../eval/evidence-debt.js";
import { resolveTestsUnderSolution } from "./legacy-fallback.js";
import type { OstNode } from "./node.js";

/** Risk, low to high — the order a reader is asked to reproduce blind. */
export const RISK_LEVELS = ["low", "medium", "high"] as const;

export type RiskLevel = (typeof RISK_LEVELS)[number];

/** The three routes, by id. Exactly three, because the node is about three. */
export const ROUTE_IDS = ["learn-first", "riskiest-belief-first", "commit-early"] as const;

export type RouteId = (typeof ROUTE_IDS)[number];

/**
 * The kinds of thing a route can foreclose.
 *
 * A closed vocabulary rather than free prose, because the distinctness check
 * ({@link foreclosureProblem}) compares trade-offs across routes and cannot
 * compare sentences. Each kind is a different way a route makes something
 * harder afterwards, and each is checkable against the tree.
 */
export const FORECLOSURE_KINDS = [
  /** A live build permit left unspent while the route measures instead. */
  "unspent-permit",
  /** A test whose reading is contaminated once the thing it judges exists. */
  "clean-read",
  /** A belief left unmeasured behind the one test this route chose to run. */
  "deferred-belief",
  /** A measurement a failure of the riskiest belief would have made moot. */
  "moot-measurement",
  /** A buildable sibling this route never builds, so it is never compared. */
  "unbuilt-comparison",
] as const;

export type ForeclosureKind = (typeof FORECLOSURE_KINDS)[number];

/** One thing taking a route makes harder to do afterwards. */
export interface Foreclosure {
  kind: ForeclosureKind;
  /** The node in the branch this forecloses on — a title, so it can be checked. */
  target: string;
  /** What is lost, stated plainly enough for an operator to disagree with. */
  what: string;
}

/** One move in a route: measure a belief, or commit to a solution. */
export interface RouteStep {
  act: "test" | "build";
  /** The AssumptionTest or Solution title this step acts on. */
  node: string;
}

/**
 * What actually chose the belief `riskiest-belief-first` goes after.
 *
 * `blast-radius` means the tree ranked it: more solutions in the branch rest on
 * this belief than on any other, so its failure really would kill more. That is
 * the only basis this module treats as a risk ranking.
 *
 * `tie-break` means nothing in the tree ranked it. Every candidate belief
 * carries the same blast radius — on a tree where each solution states its own
 * assumptions and none are shared, that is *every* branch — so the choice fell
 * through to test count and then to alphabetical order. It is still a defensible
 * route to take, and it is not a risk ranking, and saying which one it is is
 * what stops the third route being the fiction the tree node warned about.
 * Measured on this product's own vault, 2026-08-28: every branch that yields
 * three routes yields them on a `tie-break`.
 */
export type RiskiestBasis = "blast-radius" | "tie-break";

export interface Route {
  id: RouteId;
  /**
   * Derived by {@link riskOf} from `steps` — never set by a caller and never
   * carried in from anywhere. This is the field the node's objection is about.
   */
  risk: RiskLevel;
  /** One line saying what the route does, for a reader ranking them blind. */
  summary: string;
  steps: RouteStep[];
  /** Never empty: a route that forecloses nothing is not a choice. */
  forecloses: Foreclosure[];
  /**
   * Set on `riskiest-belief-first` and nowhere else: whether the tree picked its
   * belief or a tie-break did. Carried structurally rather than left in the
   * summary alone so a caller can refuse to present a `tie-break` route as a
   * risk ranking without parsing English.
   */
  basis?: RiskiestBasis;
}

/** Three routes over one branch, or the reason there are not three. */
export type BranchRoutes =
  | { kind: "routes"; branch: string; routes: Route[] }
  | ThinBranch;

/**
 * A branch that cannot support three genuinely different routes.
 *
 * Deliberately not an error and deliberately not two routes: the whole claim of
 * this feature is that three routes beat one recommendation, and a branch that
 * yields fewer is evidence against that claim on that branch. Saying so is worth
 * more than padding the list.
 */
export interface ThinBranch {
  kind: "too-thin";
  branch: string;
  /** Which route could not be built, and why — in terms of the branch's nodes. */
  why: string;
  /** The one change to the tree that would make three routes possible. */
  whatWouldHelp: string;
}

/**
 * How much of the branch a route commits before it learns anything — read off
 * the steps, which is the only place risk is allowed to come from.
 *
 * `high` when the first move is a build: everything after it is spent. `low`
 * when every measurement the branch has to offer lands before anything is
 * built. `medium` is the middle — some evidence, then commitment — and it is the
 * only one that needs `unrunTests` to identify, because "ran some of them" is
 * not visible from a step list alone.
 */
export function riskOf(steps: readonly RouteStep[], unrunTests: number): RiskLevel {
  const firstBuild = steps.findIndex((s) => s.act === "build");
  if (firstBuild === 0) return "high";
  const measuredFirst = firstBuild === -1 ? steps.filter((s) => s.act === "test").length : firstBuild;
  return measuredFirst >= unrunTests ? "low" : "medium";
}

/**
 * Why this set of routes is not a real choice, or null when it is.
 *
 * Three conditions, and each one is a way the node's own objection comes true:
 *
 *   1. **A route that forecloses nothing** is a free lunch, and a free lunch on
 *      a list of three is the recommendation the other two exist to disguise.
 *   2. **Two routes with the same foreclosed set** are one route written twice.
 *   3. **A route holding no trade-off its siblings do not** is dominated: an
 *      operator comparing costs has no reason to ever pick it, which is exactly
 *      "two of them are obviously worse".
 *
 * Identity is `kind:target`, so two routes deferring the same permit genuinely
 * share that cost — the overlap is real and is meant to be visible. What must
 * not happen is a route whose whole cost is somebody else's.
 */
export function foreclosureProblem(routes: readonly Route[]): string | null {
  const keys = routes.map((r) => new Set(r.forecloses.map((f) => `${f.kind}:${f.target}`)));

  for (let i = 0; i < routes.length; i++) {
    if (keys[i].size === 0) return `route "${routes[i].id}" forecloses nothing — a route with no cost is not a choice`;
  }
  for (let i = 0; i < routes.length; i++) {
    for (let j = i + 1; j < routes.length; j++) {
      if (keys[i].size === keys[j].size && [...keys[i]].every((k) => keys[j].has(k))) {
        return `routes "${routes[i].id}" and "${routes[j].id}" foreclose exactly the same things — that is one route written twice`;
      }
    }
  }
  for (let i = 0; i < routes.length; i++) {
    const others = keys.filter((_, j) => j !== i);
    const own = [...keys[i]].filter((k) => !others.some((o) => o.has(k)));
    if (own.length === 0) {
      return (
        `route "${routes[i].id}" forecloses nothing its siblings do not — it is dominated, ` +
        `so an operator comparing costs would never have reason to pick it`
      );
    }
  }
  return null;
}

/** Every node beneath `title`, the node itself included, with a cycle guard. */
function subtree(index: Map<string, OstNode>, title: string): OstNode[] {
  const out: OstNode[] = [];
  const seen = new Set<string>();
  const walk = (t: string): void => {
    if (seen.has(t)) return; // back edge contributes nothing, as everywhere else here
    seen.add(t);
    const node = index.get(t);
    if (!node) return; // dangling link — `check` owns reporting that
    out.push(node);
    for (const link of node.links) walk(link);
  };
  walk(title);
  return out;
}

/**
 * The belief whose failure would kill the most of the branch: the Assumption the
 * most solutions in the branch depend on — and, just as importantly, whether
 * that count is what actually chose it.
 *
 * Ties break on the number of unrun tests beneath it and then on title, so two
 * runs over one tree name the same belief — a "riskiest" that moves between runs
 * is not a risk ranking either. But a stable answer is not the same as a
 * justified one: when the top belief's blast radius is not strictly larger than
 * the runner-up's, the tie-break picked it and nothing in the tree did. That is
 * reported as {@link RiskiestBasis} rather than smoothed over, because a
 * confident sentence over an arbitrary choice is exactly the failure the tree
 * node predicted for this whole feature.
 */
function riskiestAssumption(
  assumptions: readonly OstNode[],
  dependents: Map<string, number>,
  unrun: ReadonlySet<string>,
): { assumption: OstNode; dependents: number; basis: RiskiestBasis } | undefined {
  const scored = assumptions.map((a) => ({
    a,
    solutions: dependents.get(a.title) ?? 0,
    tests: a.links.filter((l) => unrun.has(l)).length,
  }));
  scored.sort((x, y) => y.solutions - x.solutions || y.tests - x.tests || x.a.title.localeCompare(y.a.title));
  const top = scored[0];
  if (!top) return undefined;
  const runnerUp = scored[1];
  const basis: RiskiestBasis =
    runnerUp !== undefined && top.solutions > runnerUp.solutions ? "blast-radius" : "tie-break";
  return { assumption: top.a, dependents: top.solutions, basis };
}

/**
 * Three routes through one branch, or the reason there are not three.
 *
 * `branch` is an Opportunity title; the branch is that node and everything
 * beneath it. Throws only when the title is not an Opportunity at all — a real
 * branch that is simply too thin is a finding, not a caller error.
 */
export function routesFor(tree: readonly OstNode[], branch: string): BranchRoutes {
  const index = new Map(tree.map((n) => [n.title, n]));
  const root = index.get(branch);
  if (!root || root.layer !== "Opportunity") {
    throw new Error(`no Opportunity node titled "${branch}" — routes are planned over one branch of the tree`);
  }

  const nodes = subtree(index, branch);
  const solutions = nodes.filter((n) => n.layer === "Solution");
  const assumptions = nodes.filter((n) => n.layer === "Assumption");
  const unrunTests = new Set(
    nodes.filter((n) => n.layer === "AssumptionTest" && !hasRecordedResult(n)).map((n) => n.title),
  );

  const thin = (why: string, whatWouldHelp: string): ThinBranch => ({ kind: "too-thin", branch, why, whatWouldHelp });

  if (unrunTests.size === 0) {
    return thin(
      `nothing beneath "${branch}" is still unmeasured — every assumption test in it already carries a result`,
      "there is no learn-first route without a belief left to measure; write the test for a belief this branch has not risked yet",
    );
  }

  // A build permit is what makes "build now" a route rather than a wish, so the
  // same gate the build loop obeys decides it here. Reading it per solution is
  // the whole-tree read `buildPermit` already does; the branch is small.
  const buildable = solutions.filter((s) => buildPermit(tree, s.title).cleared);
  if (buildable.length === 0) {
    return thin(
      `no solution beneath "${branch}" holds a live build permit — ${solutions.length} solution(s), none of them cleared to build`,
      "there is no commit-early route with nothing to commit to; `ost-agent buildable` names what each solution is missing",
    );
  }

  const withUnrunTest = assumptions.filter((a) => a.links.some((l) => unrunTests.has(l)));
  if (withUnrunTest.length < 2) {
    return thin(
      `"${branch}" rests on ${withUnrunTest.length} belief(s) with an unmeasured test — with fewer than two, ` +
        `"test the riskiest belief first" names the same work as "test everything first"`,
      "a branch needs at least two live beliefs before choosing between them is a decision; separate the beliefs this branch conflates, or measure one of them",
    );
  }

  // Which beliefs the branch's solutions actually rest on — the count that makes
  // one of them the riskiest.
  const dependents = new Map<string, number>();
  for (const s of solutions) {
    for (const link of s.links) {
      if (index.get(link)?.layer === "Assumption") dependents.set(link, (dependents.get(link) ?? 0) + 1);
    }
  }
  const chosen = riskiestAssumption(withUnrunTest, dependents, unrunTests)!;
  const riskiest = chosen.assumption;
  const riskiestTests = riskiest.links.filter((l) => unrunTests.has(l));
  const everyTest = [...unrunTests];
  const otherTests = everyTest.filter((t) => !riskiestTests.includes(t));

  // commit-early builds the FIRST buildable solution and nothing else: committing
  // to all of them at once is not a route anybody takes, and the siblings it
  // leaves are the comparison it gives up.
  const committed = buildable[0];
  const committedTests = resolveTestsUnderSolution(committed, index)
    .map((r) => r.test.title)
    .filter((t) => unrunTests.has(t));

  const learnFirstSteps: RouteStep[] = [
    ...everyTest.map((t): RouteStep => ({ act: "test", node: t })),
    ...buildable.map((s): RouteStep => ({ act: "build", node: s.title })),
  ];
  const riskiestSteps: RouteStep[] = [
    ...riskiestTests.map((t): RouteStep => ({ act: "test", node: t })),
    ...buildable.map((s): RouteStep => ({ act: "build", node: s.title })),
  ];
  const commitSteps: RouteStep[] = [
    { act: "build", node: committed.title },
    ...everyTest.map((t): RouteStep => ({ act: "test", node: t })),
  ];

  const routes: Route[] = [
    {
      id: "learn-first",
      risk: riskOf(learnFirstSteps, unrunTests.size),
      summary: `measure all ${unrunTests.size} unmeasured belief(s) beneath "${branch}", then build what survives`,
      steps: learnFirstSteps,
      forecloses: [
        ...buildable.map((s): Foreclosure => ({
          kind: "unspent-permit",
          target: s.title,
          what:
            `"${s.title}" holds a live build permit that goes unspent while the measuring runs — a red instrument ` +
            `another pass can pick up, or that something else turns green in the meantime`,
        })),
        ...otherTests.map((t): Foreclosure => ({
          kind: "moot-measurement",
          target: t,
          what:
            `"${t}" is measured before anyone knows whether "${riskiest.title}" holds — if that belief fails, ` +
            `this reading was bought for a branch that no longer exists`,
        })),
      ],
    },
    {
      id: "riskiest-belief-first",
      risk: riskOf(riskiestSteps, unrunTests.size),
      summary:
        chosen.basis === "blast-radius"
          ? `measure "${riskiest.title}" — the belief ${chosen.dependents} solution(s) rest on, more than any other here — and decide after`
          : `measure "${riskiest.title}" first — and note that the tree did not choose it: every belief in this ` +
            `branch carries the same ${chosen.dependents} dependent solution(s), so a tie-break picked this one and ` +
            `the order is not a risk ranking`,
      basis: chosen.basis,
      steps: riskiestSteps,
      forecloses: [
        ...buildable.map((s): Foreclosure => ({
          kind: "unspent-permit",
          target: s.title,
          what: `"${s.title}" holds a live build permit that goes unspent while the one test runs`,
        })),
        ...withUnrunTest
          .filter((a) => a.title !== riskiest.title)
          .map((a): Foreclosure => ({
            kind: "deferred-belief",
            target: a.title,
            what:
              `"${a.title}" stays unmeasured behind the one test this route chose — if it is what actually breaks, ` +
              `this route found out last`,
          })),
      ],
    },
    {
      id: "commit-early",
      risk: riskOf(commitSteps, unrunTests.size),
      summary: `build "${committed.title}" now and let the measurements come in against a thing that already exists`,
      steps: commitSteps,
      forecloses: [
        ...committedTests.map((t): Foreclosure => ({
          kind: "clean-read",
          target: t,
          what:
            `"${t}" can no longer produce a clean reading — it is taken on a thing already built and already paid ` +
            `for, which is not the reading the test was designed to give`,
        })),
        ...buildable.slice(1).map((s): Foreclosure => ({
          kind: "unbuilt-comparison",
          target: s.title,
          what: `"${s.title}" is never compared against "${committed.title}" — committing early spends the comparison`,
        })),
      ],
    },
  ];

  // The invariant is checked, not assumed. A branch whose three routes collapse
  // into fewer real choices is thin in a way the counts above did not catch —
  // for instance a committed solution with no unrun test of its own and no
  // buildable sibling, which leaves commit-early with nothing to give up.
  const problem = foreclosureProblem(routes);
  if (problem) {
    return thin(
      problem,
      "these three routes collapse into fewer on this branch; give the branch a second buildable solution or a test beneath the one it would build first",
    );
  }

  return { kind: "routes", branch, routes };
}

/** Render for the terminal — the labels a blind reader would have stripped are last. */
export function renderRoutes(result: BranchRoutes): string {
  if (result.kind === "too-thin") {
    return [
      `No three routes through "${result.branch}".`,
      "",
      `Why: ${result.why}.`,
      `What would help: ${result.whatWouldHelp}.`,
      "",
      "Two routes padded to three is a recommendation wearing a costume, so this refuses instead.",
    ].join("\n");
  }

  const out = [`THREE ROUTES — ${result.branch}`, ""];
  for (const r of result.routes) {
    out.push(`## ${r.id} (risk: ${r.risk})`, "", r.summary, "", "Steps:");
    for (const [i, s] of r.steps.entries()) out.push(`  ${i + 1}. ${s.act} "${s.node}"`);
    out.push("", `Forecloses (${r.forecloses.length}):`);
    for (const f of r.forecloses) out.push(`  - [${f.kind}] ${f.what}`);
    out.push("");
  }
  out.push(
    "The risk levels above are read off each route's own steps — how much it commits before it learns anything —",
    "not assigned. Which route is right is still yours; this says what each one costs.",
  );
  // Said again at the bottom, because the summary saying it once is easy to read
  // past and this is the one claim on the page the tree cannot support.
  if (result.routes.some((r) => r.basis === "tie-break")) {
    out.push(
      "",
      "Caveat, stated because it changes what this page is worth: no belief in this branch is depended on by more",
      "solutions than any other, so riskiest-belief-first was chosen by a tie-break rather than by blast radius.",
      "It is a route you can take. It is not evidence about which belief is riskiest.",
    );
  }
  return out.join("\n");
}
